const PREGNANT_CLINICAL_FIELDS = Object.freeze([
  'altura',
  'peso_pregestacional',
  'peso_atual',
  'temperatura_materna',
  'pressao_sistole',
  'pressao_diastole',
  'antecedentes_diabetes',
  'antecedentes_hipertensao',
  'antecedentes_gemelar',
  'antecedentes_outros',
  'antecedentes_texto',
  'gestacao_partos',
  'gestacao_vaginal',
  'gestacao_cesarea',
  'gestacao_bebe_maior_45',
  'gestacao_bebe_maior_25',
  'gestacao_eclampsia_pre_eclampsia',
  'gestacao_gestas',
  'gestacao_abortos',
  'gestacao_mais_tres_abortos',
  'gestacao_nascidos_vivos',
  'gestacao_nascidos_mortos',
  'gestacao_vivem',
  'gestacao_mortos_primeira_semana',
  'gestacao_mortos_depois_primeira_semana',
  'gestacao_final_gestacao_anterior_1ano',
  'antecedentes_clinicos_diabetes',
  'antecedentes_clinicos_infeccao_urinaria',
  'antecedentes_clinicos_infertilidade',
  'antecedentes_clinicos_dific_amamentacao',
  'antecedentes_clinicos_cardiopatia',
  'antecedentes_clinicos_tromboembolismo',
  'antecedentes_clinicos_hipertensao_arterial',
  'antecedentes_clinicos_cirur_per_uterina',
  'antecedentes_clinicos_cirurgia',
  'antecedentes_clinicos_outros',
  'antecedentes_clinicos_outros_texto',
  'gestacao_atual_fumante',
  'gestacao_atual_quant_cigarros',
  'gestacao_atual_alcool',
  'gestacao_atual_outras_drogas',
  'gestacao_atual_hiv_aids',
  'gestacao_atual_sifilis',
  'gestacao_atual_toxoplasmose',
  'gestacao_atual_infeccao_urinaria',
  'gestacao_atual_anemia',
  'gestacao_atual_inc_istmocervical',
  'gestacao_atual_ameaca_parto_premat',
  'gestacao_atual_imuniz_rh',
  'gestacao_atual_oligo_polidramio',
  'gestacao_atual_rut_prem_membrana',
  'gestacao_atual_ciur',
  'gestacao_atual_pos_datismo',
  'gestacao_atual_febre',
  'gestacao_atual_hipertensao_arterial',
  'gestacao_atual_pre_eclamp_eclamp',
  'gestacao_atual_cardiopatia',
  'gestacao_atual_diabete_gestacional',
  'gestacao_atual_uso_insulina',
  'gestacao_atual_hemorragia_1trim',
  'gestacao_atual_hemorragia_2trim',
  'gestacao_atual_hemorragia_3trim',
  'exantema_rash',
  'vacina_antitetanica',
  'vacina_antitetanica_1dose',
  'vacina_antitetanica_2dose',
  'vacina_antitetanica_dtpa',
  'vacina_hepatite_b',
  'vacina_hepatite_b_1dose',
  'vacina_hepatite_b_2dose',
  'vacina_hepatite_b_3dose',
  'vacina_influenza',
  'vacina_influenza_1dose',
  'vacina_covid19',
  'vacina_covid19_1dose',
  'vacina_covid19_2dose',
  'info_gerais_edemas',
  'info_gerais_sintomas',
  'info_gerais_estado_geral_1',
  'info_gerais_estado_geral_2',
  'info_gerais_nutricional',
  'info_gerais_psicossocial',
]);

const ENCRYPTED_FIELDS = Object.freeze({
  users: Object.freeze(['name', 'email', 'birthdate']),
  doctors: Object.freeze(['crm', 'crm_estado', 'telefone']),
  pregnants: PREGNANT_CLINICAL_FIELDS,
  pregnancies: Object.freeze([
    'weeks',
    'is_checked',
    'dum',
    'dpp',
    'ccn',
    'dgm',
    'glicemia',
    'frequencia_cardiaca',
    'altura_uterina',
    'regularidade_do_ciclo',
    'ig_ultrassonografia',
  ]),
  pregnancy_events: Object.freeze(['descricao', 'data_evento']),
  pregnant_documents: Object.freeze([
    'document_name',
    'document_type',
    'extracted_text',
    'extraction_error',
    'report_comment',
  ]),
  exam_requests: Object.freeze(['exam_name', 'instructions']),
  medidas_fetais: Object.freeze([
    'ccn',
    'crl',
    'dgn',
    'idade_gestacional_semanas',
  ]),
});

const HASHED_FIELDS = Object.freeze({
  users: Object.freeze({
    password: 'bcrypt',
    email_lookup_hash: 'HMAC-SHA-256',
  }),
});

const CLEAR_FIELDS = Object.freeze({
  common: Object.freeze(['id', 'created_at', 'updated_at']),
  users: Object.freeze(['is_active', 'role', 'encryption_key_version']),
  doctors: Object.freeze([
    'user_id', 'especialidade', 'encryption_key_version',
  ]),
  pregnants: Object.freeze(['user_id', 'encryption_key_version']),
  pregnancies: Object.freeze(['pregnant_id', 'encryption_key_version']),
  pregnancy_events: Object.freeze([
    'pregnancy_id', 'encryption_key_version',
  ]),
  pregnant_documents: Object.freeze([
    'pregnant_id',
    'exam_request_id',
    'file_path',
    'file_encryption_version',
    'extraction_status',
    'extraction_method',
    'extraction_confidence',
    'extraction_attempts',
    'extracted_at',
    'uploaded_at',
    'status',
    'reviewed_by_user_id',
    'reviewed_at',
    'encryption_key_version',
  ]),
  exam_requests: Object.freeze([
    'pregnant_id',
    'doctor_id',
    'status',
    'requested_at',
    'cancelled_at',
    'encryption_key_version',
  ]),
  doctor_patient_links: Object.freeze([
    'doctor_id', 'pregnant_id', 'status',
  ]),
  medidas_fetais: Object.freeze(['encryption_key_version']),
});

function getEncryptedFields(table) {
  return ENCRYPTED_FIELDS[table] || [];
}

module.exports = {
  CLEAR_FIELDS,
  ENCRYPTED_FIELDS,
  HASHED_FIELDS,
  PREGNANT_CLINICAL_FIELDS,
  getEncryptedFields,
};
